# run: conda env create --file environments.yml
name: atcoder
channels:
  - conda-forge
dependencies:
  # for pycaret
  - python==3.8
  # for Open3D
  - pip>=20.3
  - pip:
    - online-judge-tools
    - selenium