version: '3'

services:
  atcoder:
    image: local/atcoder:230311
    build:
      context: .
      dockerfile: ubuntu.dockerfile
    tty: true
    restart: always

    volumes:
      - ../src:/workspace/src
      - ../.vscode:/workspace/.vscode
      - ../config/activate.zsh:/home/${USERNAME}/.zshrc
