version: '3'

services:
  atcoder:
    image: local/atcoder:230311
    build:
      context: .
      dockerfile: mac.dockerfile
    tty: true
    restart: always

    volumes:
      - ../src:/root/src
      - ./activate.sh:/root/.zshrc
