version: '3'

services:
  atcoder:
    image: local/atcoder:230311
    build:
      context: .
      target: atcoder_base
    tty: true
    restart: always

    volumes:
      - ../:/workspace
      - ../README.md:/workspace/README.md
      - ../config/activate.zsh:/root/.zshrc
