version: '3'

services:
  atcoder:
    image: local/atcoder:230311
    build:
      context: .
      dockerfile: Dockerfile
      # Read variables from .env
      # cf. https://docs.docker.jp/compose/environment-variables.html
      args:
        - UID=${UID}
        - GID=${GID}
        - USERNAME=${USERNAME}
        - GROUPNAME=${GROUPNAME}
    user: "${UID}:${GID}"
    tty: true
    restart: always

    # cf. http://wiki.ros.org/docker/Tutorials/GUI#login_as_yourself
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../src:/home/${USERNAME}/src
      - ../.vscode:/home/${USERNAME}/.vscode
      - ../config/activate.zsh:/home/${USERNAME}/.zshrc
