version: '3'

services:
  atcoder:
    image: local/atcoder:230311
    build:
      context: .
    # 標準入出力のデバイスを有効化. fg プロセス無しでも終了しない.
    tty: true
    # ホスト側の再起動似合わせてコンテナも再起動
    restart: always

    volumes:
      # リポジトリ全体をマウント.
      - ../:/workspace
